language: php
dist: precise

php:
  - 7.0

env:
  global:
    - PATH=$PATH:/home/travis/.composer/vendor/bin:$TRAVIS_BUILD_DIR/vendor/bin

install:
  - composer self-update
  - composer install

script:
  - grumphp run
  - phpunit

notifications:
  email: false
